[workspace]
members = ["crates/analysis", "crates/collector", "crates/cli"]
resolver = "2"

[workspace.package]
version = "0.1.4"
edition = "2021"
license = "GPL-3.0-or-later"
repository = "https://github.com/crazycat256/sinksight-engine"

[profile.release]
lto = true
codegen-units = 1
strip = true
